DROP TABLE IF EXISTS items;
DROP TYPE IF EXISTS unit;

CREATE TYPE unit AS ENUM (
    'pounds', 'ounces', 'cups', 'pints', 'gallons', 'teaspoons', 'tablespoons',
    'each', 'quarts'
);

CREATE TABLE items (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name TEXT NOT NULL
);