DROP TABLE IF EXISTS recipes;
DROP TYPE IF EXISTS category;

CREATE TYPE category AS ENUM (
    'breakfast', 'lunch', 'side', 'main', 'dessert'
);

CREATE TABLE recipes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category category NOT NULL,
    rating SMALLINT DEFAULT 0
);