DROP TABLE IF EXISTS mealplan;

CREATE TABLE mealplan (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_id INTEGER REFERENCES recipes(id),
    item_id INTEGER REFERENCES items(id),
    qty REAL NOT NULL,
    unit unit 
)